config/routes.rb
Rails.application.routes.draw do
  resources :user_likes
  resources :comments
  resources :libraries, constraints: ->(request){ !request.format.html? }
  devise_for :users
  
  resources :charges, only: [:new, :create]
  get :search, controller: :main
  get '*path', to: 'pages#protected', constraints: ->(request){ request.format.html? }
  root to: 'pages#unprotected'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    has_one :user, through: :library
end

app/models/library.rb
class Library < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :user_likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :libraries
end

app/models/user_like.rb
class UserLike < ApplicationRecord
    has_one :user, through: :library
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path
    end
  end

  def after_sign_in_path_for(resource)
    '/cards'
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_up_path_for(resource)
    '/cards'
  end

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
 end
end

app/controllers/authorization_controller.rb
class AuthorizationController < ApplicationController                                          
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    # Amount in cents
    @amount = 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source => params[:stripeToken]
      )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Tip The Creator',
      :currency => 'usd'
      )

    redirect_to '/cards'

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ActionController::API
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    comment = Comment.create(comment_params)
    if comment.valid?
      render json: comment
     else
       render json: comment.errors, status: :unprocessable_entity
     end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :library_id, :user_id)
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ActionController::API
  before_action :set_library, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  include ApplicationHelper

  # GET /libraries
  # GET /libraries.json
  def index
    @user = User.all

    @libraries = Library.all.order('created_at ASC')
    @comments = Comment.all
    @user_likes = UserLike.all
    render :json => @libraries, :include => [:user, :comments, :user_likes]
   

  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    @libraries = libraries.find(params[:id])
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = current_user.libraries.create(library_params)
    render json: @library
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    library = Library.find(params[:id])
    library.update_attributes(library_params)
    render json: library
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library = Library.find(params[:id])
    @library.destroy
    render json: @library
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:title, :markdown, :desc, :likes)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate_user!, only: :protected
    
    def unprotected
    end

    def protected
    end
end

app/controllers/user_likes_controller.rb
class UserLikesController < ActionController::API
  before_action :set_user_like, only: [:show, :edit, :update, :destroy]

  # GET /user_likes
  # GET /user_likes.json
  def index
    @user_likes = UserLike.all
  end

  # GET /user_likes/1
  # GET /user_likes/1.json
  def show
  end

  # GET /user_likes/new
  def new
    @user_like = UserLike.new
  end

  # GET /user_likes/1/edit
  def edit
  end

  # POST /user_likes
  # POST /user_likes.json
  def create
    user_like = UserLike.create(user_like_params)
    if user_like.valid?
      render json: user_like
     else
       render json: user_like.errors, status: :unprocessable_entity
     end
  end

  # PATCH/PUT /user_likes/1
  # PATCH/PUT /user_likes/1.json
  def update
    respond_to do |format|
      if @user_like.update(user_like_params)
        format.html { redirect_to @user_like, notice: 'User like was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_like }
      else
        format.html { render :edit }
        format.json { render json: @user_like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_likes/1
  # DELETE /user_likes/1.json
  def destroy
    @user_like.destroy
    respond_to do |format|
      format.html { redirect_to user_likes_url, notice: 'User like was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_like_params
      params.require(:lul).permit(:user_id, :library_id, :value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class 
     User 
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end
 

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_likes_helper.rb
module UserLikesHelper
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
	<%= yield %>
</body>
</html>	

app/views/charges/create.html.erb
<h3>Thank you! Your tip transaction of $1.00 was successful!</h3>
<p>The creator will receive the tip within 5 business days.</p>

<button><%= link_to "Take Me Back", '/cards' %></button>

app/views/charges/new.html.erb
<div class="newtip">
	<%= form_tag charges_path do %>
		<div>
			<% if flash[:error].present? %>
			<div id="error_explanation">
				<p><%= flash[:error] %></p>
			</div>
			<% end %>
			<span class="amount">Amount: $1.00</span>
		</div>

		<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
			data-description="Tip The Creator"
			data-amount="100"
			data-locale="auto">
		</script>
		
		<a href="/cards" class="backbutton">Go Back</a>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.number_field :card_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.card_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @comment.card_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Syntax Solutions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= yield %>
	<%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/libraries/_form.html.erb
<%= form_with(model: library, local: true) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :markdown %>
    <%= form.text_field :markdown %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
# <p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Markdown</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.title %></td>
        <td><%= library.desc %></td>
        <td><%= library.markdown %></td>
        <td><%= library.user_id %></td>
        <td><%= link_to 'Show', library %></td>
        <td><%= link_to 'Edit', edit_library_path(library) %></td>
        <td><%= link_to 'Destroy', library, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
# <p id="notice"><%= notice %></p>

# <p>
#   <strong>Title:</strong>
#   <%= @library.title %>
# </p>

# <p>
#   <strong>Desc:</strong>
#   <%= @library.desc %>
# </p>

# <p>
#   <strong>Markdown:</strong>
#   <%= @library.markdown %>
# </p>

# <p>
#   <strong>User:</strong>
#   <%= @library.user_id %>
# </p>

# <%= link_to 'Edit', edit_library_path(@library) %> |
# <%= link_to 'Back', libraries_path %>


# <div id="content">
#   <%= markdown @libraries.content %>
# </div>

app/views/pages/protected.html.erb
<%= react_component('AuthenticatedApp', current_user: current_user) %>

app/views/pages/unprotected.html.erb
<%= react_component('UnauthenticatedApp') %>

<!-- Log in -->
<div class="login hidden">
  <%= form_for(:user, :url => session_path(:user)) do |f| %>
    <div class="ui left icon input">
      <i aria-hidden="true" class="mail icon"></i>
      <%= f.text_field :email, autofocus: true, autocomplete: "email", placeholder: "Email" %>
    </div>
		<div class="ui left icon input">
			<i aria-hidden="true" class="lock icon"></i>
      <%= f.password_field :password, autocomplete: "current-password", placeholder: "Password" %>
    </div>
    
    <div class="actions">
      <%= f.submit "Login", class: "ui white inverted button" %>
    </div>
    
    <div class="memory">
			<div class="ui checkbox"><%= f.check_box :remember_me, class: "hidden" %><%= f.label :remember_me %></div><br />
      <%= link_to "Forgot your password?", new_password_path(:user) %>
    </div>
  <% end %>
</div>
<!-- End of Log in -->

<div class="landing container hidden">
  <div class="ui stackable very relaxed two column grid">
    <div class="column">
        <!-- About -->
        <div class="about">
					<h2>Syntax Solutions</h2>
					<h3>Understanding coding solutions the simple way.</h3>
					<p>We, as students at a coding bootcamp, were inspired to create this site to help save ourselves the hours we were pouring into searching the web to try to solve the syntax errors that were keeping us from progessing.</p>
					<p> As a group we wanted to create a site that was simple and easy to digest the definitions as well as coding examples to better grasp the idea and or concept as well as serve those who visually learn.</p>
        </div>
        <!-- End of About -->
    </div>
    <div class="middle aligned column">
      <!-- Sign Up -->
      <div class="signup">
        <h2>Signup</h2>
    
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
    
          <div class="ui left icon input">
	          <i aria-hidden="true" class="user icon"></i>
            <%= f.text_field :user_name, autocomplete: "user_name",  placeholder: "Username"%>
          </div>
    
          <div class="ui left icon input">
            <i aria-hidden="true" class="mail icon"></i>
            <%= f.email_field :email, autocomplete: "email", placeholder: "Email" %>
          </div>
    
          <div class="ui left icon input">
            <i aria-hidden="true" class="lock icon"></i>
            <%= f.password_field :password, autocomplete: "current-password", placeholder: "Password" %>
          </div>
    
          <div class="ui left icon input">
            <i aria-hidden="true" class="lock icon"></i>
            <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
          </div>
    
          <div class="field">
            <%= f.submit "Signup", class: "ui violet button" %>
          </div>
        <% end %>
      </div>
      <!-- End of Sign Up -->
    </div>
  </div>
  <div class="ui vertical divider">
    <i aria-hidden="true" class="code icon"></i>
  </div>
</div>

app/views/user_likes/_form.html.erb
<%= form_with(model: user_like, local: true) do |form| %>
  <% if user_like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_like.errors.count, "error") %> prohibited this user_like from being saved:</h2>

      <ul>
      <% user_like.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :library_id %>
    <%= form.number_field :library_id %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_likes/edit.html.erb
<h1>Editing User Like</h1>

<%= render 'form', user_like: @user_like %>

<%= link_to 'Show', @user_like %> |
<%= link_to 'Back', user_likes_path %>

app/views/user_likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Likes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Library</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_likes.each do |user_like| %>
      <tr>
        <td><%= user_like.user_id %></td>
        <td><%= user_like.library_id %></td>
        <td><%= user_like.value %></td>
        <td><%= link_to 'Show', user_like %></td>
        <td><%= link_to 'Edit', edit_user_like_path(user_like) %></td>
        <td><%= link_to 'Destroy', user_like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Like', new_user_like_path %>

app/views/user_likes/new.html.erb
<h1>New User Like</h1>

<%= render 'form', user_like: @user_like %>

<%= link_to 'Back', user_likes_path %>

app/views/user_likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_like.user_id %>
</p>

<p>
  <strong>Library:</strong>
  <%= @user_like.library_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @user_like.value %>
</p>

<%= link_to 'Edit', edit_user_like_path(@user_like) %> |
<%= link_to 'Back', user_likes_path %>